
format compact

!rm last_objs/*.o *.mexa64;  

display('building')

%        'pltf/pltf.cu pltf/pltf_par.cu pltf/pltf_seq.cu ' ...
%        'gctf/gctf.cu gctf/gctf_par.cu gctf/gctf_seq.cu ' ...

cmd = [ '/home/can/arastir/cuda2/cudainstall/4.1/cuda/bin/nvcc -c -g' ...
        ' -arch sm_13 -Xcompiler -fPIC -I /home/can/bin/matlab_64/extern/include '...
        '-I /home/can/arastir/cuda2/cudainstall/4.1/NVIDIA_GPU_Computing_SDK/C/common/inc/ '...
        '-I common/ '...
        'common/tensorop_seq.cu common/utils.cu '...
        'common/tensorop_par.cu common/kernels.cu ' ...
        'gctf/gctf.cu gctf/gctf_par.cu gctf/gctf_seq.cu ' ...
        'custom/umut01.cu custom/umut01_par.cu' ...
      ]
unix(cmd);
% 'gmult/gmult_seq.cu '...
% 'gmult/gmult.cu ' ...
% 'gmult/gmult_par.cu ' ...
% ' gctf/gctf.cu gctf/gctf_par.cu gctf/gctf_seq.cu'

%display('linking gmult_seq')
%mex -cxx -largeArrayDims -o gmult_seq ...
%    utils.o ...
%    tensorop_seq.o ...
%    tensorop_par.o ...
%    kernels.o ...
%    gmult.o ...
%    gmult_seq.o ...
%    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
%    common/cutil/cutil.cpp.o ...
%    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
%    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
%    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft
%
%
%display('linking gmult_par')
%mex -cxx -largeArrayDims -o gmult_par ...
%    utils.o ...
%    tensorop_seq.o ...
%    tensorop_par.o ...
%    gmult.o ...
%    gmult_par.o ...
%    kernels.o ...
%    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
%    common/cutil/cutil.cpp.o ...
%    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
%    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
%    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft


%display('linking pltf_par')
%mex -cxx -largeArrayDims -o pltf_par ...
%    utils.o ...
%    tensorop_seq.o ...
%    tensorop_par.o ...
%    pltf.o ...
%    pltf_par.o ...
%    kernels.o ...
%    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
%    common/cutil/cutil.cpp.o ...
%    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
%    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
%    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft



%display('linking pltf_seq')
%mex -cxx -largeArrayDims -o pltf_seq ...
%    utils.o ...
%    tensorop_seq.o ...
%    tensorop_par.o ...
%    pltf.o ...
%    pltf_seq.o ...
%    kernels.o ...
%    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
%    common/cutil/cutil.cpp.o ...
%    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
%    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
%    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft


display('linking gctf_par')
mex -cxx -largeArrayDims -o gctf_par ...
    utils.o ...
    tensorop_seq.o ...
    tensorop_par.o ...
    gctf.o ...
    gctf_par.o ...
    kernels.o ...
    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
    common/cutil/cutil.cpp.o ...
    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart ...
    -lcufft -lcuda


display('linking umut01_par')
mex -cxx -largeArrayDims -o umut01_par ...
    utils.o ...
    tensorop_seq.o ...
    tensorop_par.o ...
    kernels.o ...
    umut01.o ...
    umut01_par.o ...
    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
    common/cutil/cutil.cpp.o ...
    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart ...
    -lcufft -lcuda


%display('linking gctf_seq')
%mex -cxx -largeArrayDims -o gctf_seq ...
%    utils.o ...
%    tensorop_seq.o ...
%    tensorop_par.o ...
%    gctf.o ...
%    gctf_seq.o ...
%    kernels.o ...
%    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
%    common/cutil/cutil.cpp.o ...
%    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
%    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
%    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft
%

!mv *.o last_objs
