
format compact

!rm last_objs/*.o *.mexa64;  

display('building')

cmd = [ '/home/can/arastir/cuda2/cudainstall/4.1/cuda/bin/nvcc -c -g' ...
        ' -arch sm_13 -Xcompiler -fPIC -I /home/can/bin/matlab_64/extern/include '...
        '-I /home/can/arastir/cuda2/cudainstall/4.1/NVIDIA_GPU_Computing_SDK/C/common/inc/ '...
        'common/utils.cu '...
        'gmult/gmult.cu ' ...
        'common/tensorop_seq.cu gmult/gmult_seq.cu '...
        'common/tensorop_par.cu common/kernels.cu gmult/gmult_par.cu ' ...
        'pltf/pltf.cu pltf/pltf_par.cu pltf/pltf_seq.cu' ...
      ]
unix(cmd);


display('linking gmult_seq')
mex -cxx -largeArrayDims -o gmult_seq ...
    utils.o ...
    tensorop_seq.o ...
    tensorop_par.o ...
    kernels.o ...
    gmult.o ...
    gmult_seq.o ...
    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
    common/cutil/cutil.cpp.o ...
    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft


display('linking gmult_par')
mex -cxx -largeArrayDims -o gmult_par ...
    utils.o ...
    tensorop_seq.o ...
    tensorop_par.o ...
    gmult.o ...
    gmult_par.o ...
    kernels.o ...
    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
    common/cutil/cutil.cpp.o ...
    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft


display('linking pltf_par')
mex -cxx -largeArrayDims -o pltf_par ...
    utils.o ...
    tensorop_seq.o ...
    tensorop_par.o ...
    pltf.o ...
    pltf_par.o ...
    kernels.o ...
    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
    common/cutil/cutil.cpp.o ...
    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft


display('linking pltf_seq')
mex -cxx -largeArrayDims -o pltf_seq ...
    utils.o ...
    tensorop_seq.o ...
    tensorop_par.o ...
    pltf.o ...
    pltf_seq.o ...
    kernels.o ...
    common/cutil/bank_checker.cpp.o common/cutil/cmd_arg_reader.cpp.o ...
    common/cutil/cutil.cpp.o ...
    common/cutil/multithreading.cpp.o common/cutil/param.cpp.o ...
    common/cutil/stopwatch.cpp.o common/cutil/stopwatch_linux.cpp.o  ...
    -L /home/can/arastir/cuda2/cudainstall/4.1/cuda/lib64 -lcudart -lcufft


!mv *.o last_objs