Description of PLTFModel
PLTFModel
PURPOSE
Represents data required to describe a tensor factorization model
SYNOPSIS
This is a script file.
DESCRIPTION
 Represents data required to describe a tensor factorization model
   A model is represented with its name and factors array of
   TFFactor objects. dims array of TFDimension objects define
   dimensions used by this model. Dimensions are transfered to C++
   in the order defined in dims array. See examples below for a
   full model description.
   Examples:
   dim_i = TFDimension('name', 'i', 'cardinality', 5);
   dim_j = TFDimension('cardinality', 6, 'name', 'j');
   dim_k = TFDimension('cardinality', 7, 'name', 'k');
   dim_r = TFDimension('cardinality', 10, 'name', 'r');
   p_A=TFFactor('name', 'p_A', 'type', 'latent', 'dims', [dim_i dim_r]);
   p_B=TFFactor('name', 'p_B', 'type', 'latent', 'dims', [dim_j dim_r]);
   p_C=TFFactor('name', 'p_C', 'type', 'latent', 'dims', [dim_k dim_r]);
   parafac_model = PLTFModel('name', 'Parafac', 'factors', [p_A p_B p_C X], 'dims', [dim_i dim_j dim_k dim_r]);
   parafac_model.rand_init_latent_factors('all');
   See also TFDimension, TFFactor
CROSS-REFERENCE INFORMATION
This function calls:
GTMGraph Represents a graph of PLTFModel objects.
PLTFModel Represents data required to describe a tensor factorization model
TFDimension Represents a single dimension
TFFactor Represents a PLTF factor
TFOCSCache Represents cached search results for optimal contraction sequence search operation
This function is called by:
GCTFModel Represents data required to describe a GCTF model
GTMGraph Represents a graph of PLTFModel objects.
PLTFModel Represents data required to describe a tensor factorization model
TFOCSCache Represents cached search results for optimal contraction sequence search operation
SUBFUNCTIONS
function obj = PLTFModel(varargin)
function [] = pltf_optimal_dot(obj, filename)
function [ dot_data ] = pltf(obj, iternum, contract_type,
function [ kl cost dot_data ] = pltf_iteration(obj,
function [ dot_data cost ] = delta(obj, alpha,
function [graph] = schedule_dp(obj)
function [newmodel ] = contract_all(obj, contract_type,
function [newmodel] = contract_full(obj, operation_type,
function [newmodel] = contract(obj, dim, operation_type,
function [ocs_dims] = get_optimal_contraction_sequence_dims(obj,
function [obj] = update_cost_from_temp(obj)
function [obj] = update_cost_from_latent(obj)
function [dn fn all_edges] = print_ubigraph(obj)
function [size] = get_element_size(obj)
function [card] = get_index_card(obj, index_char)
function [factor] = get_first_non_observed_factor(obj)
function [ind] = get_first_non_observed_factor_index(obj)
function [ind] = find_cell_char(obj, chars)
function [r] = get_dimension_index(obj, dim)
function [ordered_index_chars] = order_dims(obj,
function [alldims] = get_all_used_dims(obj)
function [contract_dims] = get_contraction_dims(obj)
function [contract_dims] = get_current_contraction_dims(obj)
function [factor_inds] = latent_factor_indices(obj)
function [factors] = latent_factors(obj)
function [factor_ind] = observed_factor_index(obj)
function [factor] = observed_factor(obj)
function [factors] = observed_factors(obj)
function [factors] = input_factors(obj)
function [factors] = temp_factors(obj)
function [index] = get_factor_index(obj, factor)
function [name] = get_factor_data_name(obj, index)
function [code_name] = get_coded_factor_name(obj, index)
function [] = rand_init_latent_factors(obj, type, imax)
function [r] = eq(a,b)
function [] = full_pltf_mem_analysis(obj)
function [] = optimal_pltf_mem_analysis(obj)
SOURCE CODE
% Represents data required to describe a tensor factorization model
%
%   A model is represented with its name and factors array of
%   TFFactor objects. dims array of TFDimension objects define
%   dimensions used by this model. Dimensions are transfered to C++
%   in the order defined in dims array. See examples below for a
%   full model description.
%
%   Examples:
%
%   dim_i = TFDimension('name', 'i', 'cardinality', 5);
%   dim_j = TFDimension('cardinality', 6, 'name', 'j');
%   dim_k = TFDimension('cardinality', 7, 'name', 'k');
%   dim_r = TFDimension('cardinality', 10, 'name', 'r');
%
%   p_A=TFFactor('name', 'p_A', 'type', 'latent', 'dims', [dim_i dim_r]);
%   p_B=TFFactor('name', 'p_B', 'type', 'latent', 'dims', [dim_j dim_r]);
%   p_C=TFFactor('name', 'p_C', 'type', 'latent', 'dims', [dim_k dim_r]);
%
%   parafac_model = PLTFModel('name', 'Parafac', 'factors', [p_A p_B p_C X], 'dims', [dim_i dim_j dim_k dim_r]);
%
%   parafac_model.rand_init_latent_factors('all');
%
%   See also TFDimension, TFFactor
classdef PLTFModel
    properties
        name = '';            % name of the model
        factors = [TFFactor]; % array of TFFactor
        dims = TFDimension; % array of TFDimension used by factors defines
                            % order of dimensions on memory
        cost = 0;
    end
    methods
        function obj = PLTFModel(varargin)
            p = inputParser;
            addParamValue(p, 'name', '', @isstr);
            addParamValue(p, 'factors', [], @isvector);
            addParamValue(p, 'dims', [], @isvector);
            parse(p,varargin{:});
            % check if all dims elements are TFDimension objects
            for i = 1:length(p.Results.dims)
                if ~isa(p.Results.dims(i), 'TFDimension')
                    err = MException( ...
                        ['PLTFModel:DimensionNotTFDimension'], ...
                        ['Dimensions of PLTFModel must be ' ...
                         'TFDimension objects']);
                    throw(err);
                end
            end
            obj.dims = p.Results.dims;
            % check if all factors are TFFactor objects
            for i = 1:length(p.Results.factors)
                if ~isa(p.Results.factors(i), 'TFFactor')
                    err = MException( ...
                        ['PLTFModel:FactorsNotTFFactor'], ...
                        ['Factors of PLTFModel must be ' ...
                         'TFFactor objects']);
                    throw(err);
                end
            end
            obj.factors = p.Results.factors;
            obj.name = p.Results.name;
        end
        function [] = pltf_optimal_dot(obj, filename)
        % Calls PLTF function and collects output of print_dot from
        % each GTM operation and plots in a single graph
            global last_node_id;
            last_node_id = 1;
            dot_str = obj.pltf(1, 'optimal', 'mem_analysis', ...
                               'yes');
            str = [ 'digraph structs{' char(10) ...
                    'rankdir=LR;' char(10) ...
                    'node [shape=plaintext];' char(10) ...
                    'splines=false; ' char(10)];
            cmd = [ 'echo ''' str char(10) dot_str ...
                    '}'' | dot -T svg ' ];
            if nargin == 2
                system([ cmd ' -o ' filename ]);
            else
                system([ cmd ' | display ' ]);
            end
        end
        function [ dot_data ] = pltf(obj, iternum, contract_type, ...
                                     operation_type, ...
                                     return_dot_data)
        % performs PLTF update operations on the model
        % returns estimated TFFactor (\hat(X))
        %
        % iternum: number of iterations
        %
        % contract_type: if equals to 'optimal', contractions are
        % performed in least memory using sequence defines order of
        % contraction operations, if equals to 'full', full tensor
        % is used for contraction operations instead of generating
        % temporary factors.
        %
        % operation_type: if equals to 'compute' normal contraction
        % operations are performed. if equals to 'mem_analysis'
        % operation are not performed but memory requirement is
        % calculated and reported. In 'mem_analysis' mode iternum
        % argument is not considered only a single iteration is
        % performed.
        %
        % return_dot_data: if equals to 'yes' then dot data for all
        % generalized tensor multiplication operations are returned
        % in a string. In this case contract_type is expected to be
        % equal to 'optimal', operation_type is expected to be
        % equal to 'mem_analysis', iternum is expected to be equal
        % to 1 . See pltf_optimal_dot function for example usage.
            if nargin == 2
                contract_type = '';
            end
            if nargin < 4
                operation_type = 'compute';
            end
            if nargin < 5
                return_dot_data = 'no';
            end
            dot_data = '';
            % init optimal model cache
            global ocs_cache;
            ocs_cache = [];
            % initalize obj.cost with memory requirements of the
            % model elements
            obj.cost = obj.get_element_size();
            display( [ 'obj.cost ' num2str(obj.cost) ] );
            hat_X = obj.observed_factor;
            hat_X.name = 'hat_X';
            % hat_X requires extra memory
            obj.cost = obj.cost + hat_X.get_element_size();
            display( [ 'obj.cost ' num2str(obj.cost) ] );
            if strcmp( operation_type, 'compute' )
                eval( [ 'global ' obj.get_factor_data_name( obj.observed_factor) ...
                        ';' ] );
                global hat_X_data;
                hat_X.rand_init(obj.dims, 100);
            end
            mask = obj.observed_factor;
            mask.name = 'mask';
            % mask requires extra memory
            obj.cost = obj.cost + mask.get_element_size();
            display( [ 'obj.cost ' num2str(obj.cost) ] );
            if strcmp( operation_type, 'compute' )
                global mask_data;
                mask_data = ones(size(hat_X_data));
                KL=zeros(1,iternum);
                for iter = 1:iternum
                    display(['iteration' char(9) num2str(iter)]);
                    [ kl cost ] = obj.pltf_iteration(contract_type, ...
                                                     hat_X, ...
                                                     mask, ...
                                                     operation_type);
                    KL(iter) = kl;
                end
                display(['KL divergence over iterations: ']);
                display(KL);
                plot(KL);
                title('KL divergence over iterations');
                xlabel('iteration number');
                ylabel('KL divergence');
            elseif strcmp( operation_type, 'mem_analysis' )
                [ kl cost dot_data ] = ...
                    obj.pltf_iteration(contract_type, hat_X, ...
                                       mask, ...
                                       operation_type, ...
                                       return_dot_data );
            end
            obj.cost = obj.cost + cost;
            display( ['e9 ' num2str(obj.cost) ' <- ' num2str(cost) ] );
            if strcmp( contract_type, 'full' )
                global F_size;
                obj.cost = obj.cost + F_size;
                display([ 'e10 ' num2str(obj.cost) ' <- ' ...
                          num2str(F_size) ]);
            end
            display([char(10) ...
                     'data elements required: ' num2str(obj.cost) ...
                     char(10) ...
                     ['memory size with (8 byte) double precision: ' ...
                      num2str(8 * obj.cost / 1000 / 1000) ' MB' ] ] );
        end
        function [ kl cost dot_data ] = pltf_iteration(obj, ...
                                                   contract_type, ...
                                                   hat_X, mask, ...
                                                   operation_type, ...
                                                   return_dot_data )
            % helper function for the pltf inner loop
            % operation_type: 'compute' if actual computation is
            % requested, 'mem_analysis' if only memory usage
            % computation is requested
            %
            % returns KL divergence value calculated at the end of
            % the operations. dot_data contains
            % graphviz data for the generalized tensor
            % multiplication operations if return_dot_data is equal
            % to 'yes'.
            if nargin < 6
                return_dot_data = 'no';
            end
            dot_data = '';
            cost = 0;
            for alpha=1:length(obj.latent_factor_indices)
                % access global data
                X_name = obj.get_factor_data_name( obj.observed_factor );
                eval( [ 'global ' X_name ';' ] );
                hat_X_data_name = obj.get_factor_data_name( hat_X );
                eval( [ 'global '  hat_X_data_name ';'] );
                mask_name =  obj.get_factor_data_name( mask );
                eval( [ 'global ' mask_name ';' ] );
                % recalculate hat_X
                newmodel = obj;
                % only not used if full, compute, no (so do it
                % always) was under if below
                graph = newmodel.schedule_dp();
                if strcmp(return_dot_data, 'yes')
                    global last_node_id;
                    [str last_node_id] = graph.print_dot(last_node_id, ...
                                                         're-calculate hat_X');
                    dot_data = [ str char(10) dot_data ];
                    global oru_models;
                    if ~length(oru_models)
                        oru_models = [ newmodel ];
                    end
                end
                % perform contraction
                % store result in hat_X_data
                [ ~ ] = ...
                    newmodel.contract_all(contract_type, ...
                                          operation_type, ...
                                          hat_X_data_name, graph);
                if strcmp(contract_type, 'optimal')
                    % does not work on 'full' contraction
                    cost = cost + graph.get_optimal_path_cost();
                end
                display( ['e1 X_hat ' num2str(cost) ' <- ' ...
                          num2str(graph.get_optimal_path_cost()) ...
                         ] );
                %result_name = ...
                %    newmodel.get_first_non_observed_factor() ...
                %    .get_data_name();
                %eval(['global ' result_name ';'] );
                %eval(['hat_X_data = ' result_name ';' ] );
                % store X / hat_X in hat_X data
                if strcmp( operation_type, 'compute' )
                    eval( [ hat_X_data_name '  =  ' ...
                            X_name ...
                            ' ./ ' ...
                            hat_X_data_name ' ;' ] );
                end
                % generate D1
                [ dd c ] = obj.delta(alpha, 'D1_data', ...
                                        contract_type, ...
                                        operation_type, ...
                                        hat_X, ...
                                        return_dot_data );
                if strcmp( return_dot_data, 'yes')
                    dot_data = [ dd char(10) dot_data ];
                end
                Z_alpha_name = obj.get_factor_data_name( ...
                    obj.factors(alpha) );
                eval( [ 'global ' Z_alpha_name ';' ] );
                if strcmp(contract_type, 'optimal')
                    cost = cost + c + ...
                           global_data_size(Z_alpha_name);
                else
                    % for full contraction type
                    cost = cost + global_data_size(Z_alpha_name);
                end
                display( ['e2 D1 Z_' num2str(alpha) ' ' num2str(cost) ' c ' ...
                          num2str(c) ' ' num2str(global_data_size(Z_alpha_name)) ...
                         ] );
                % generate D2
                [ dd ] = obj.delta(alpha, 'D2_data', ...
                                   contract_type, ...
                                   operation_type, ...
                                   mask, ...
                                   return_dot_data);
                if strcmp( return_dot_data, 'yes')
                    dot_data = [ dd char(10) dot_data ];
                end
                % works for both optimal and full contraction
                cost = cost + global_data_size(Z_alpha_name);
                display( ['e2 D1 Z_' num2str(alpha) ' ' num2str(cost) ' ' ...
                          num2str(global_data_size(Z_alpha_name)) ...
                         ] );
                % update Z_alpha
                if strcmp( operation_type, 'compute' )
                    global D1_data D2_data;
                    eval( [ Z_alpha_name '=' Z_alpha_name ' .* ' ...
                            'D1_data'                     ' ./ ' ...
                            'D2_data ;' ] );
                end
            end
            if strcmp( operation_type, 'compute' )
                % calculate KL divergence
                eval ( [ 'kl = sum(sum(sum( (' hat_X_data_name ' .* ' X_name ') .* ' ...
                         ' (log( (' hat_X_data_name ' .* ' X_name ') ) - ' ...
                         'log(' X_name ...
                         ') ) - ( ' hat_X_data_name ' .* ' X_name ')' ...
                         '+ ' X_name ...
                         ')));' ]);
            else
                kl = 0;
            end
        end
        function [ dot_data cost ] = delta(obj, alpha, ...
                                                output_name, ...
                                                contract_type, ...
                                                operation_type, ...
                                                A, return_dot_data)
        % PLTF delta function implementation
        % alpha: index of latent factor in PLTFModel.factors array
        % which will be updated
        % name: unique name used as the name of calculated delta
        % factor data
        % contract_type: see description in pltf function
        % A: operand element of delta function assumed all ones if
        % not given
        %
        % dot_data contains
        % graphviz data for the generalized tensor
        % multiplication operations if return_dot_data is equal
        % to 'yes'.
            if nargin < 7
                return_dot_data = 'no';
            end
            dot_data = '';
            % create new model for delta operation
            d_model = obj;
            % remove observed factor
            d_model.factors(d_model.observed_factor_index) = [];
            % add Z_alpha as new observed factor
            d_model.factors(alpha).isLatent = 0;
            d_model.factors(alpha).isObserved= 1;
            % if given, add A as a new latent factor
            if nargin == 7
                A.isLatent = 1;
                A.isObserved = 0;
                d_model.factors = [d_model.factors A];
            end
            % only not used if full, compute, no (so do it
            % always) was under if below
            graph = d_model.schedule_dp();
            if strcmp(return_dot_data, 'yes')
                global last_node_id;
                title = ['alpha ' num2str(alpha) ' ' ...
                         output_name ];
                [ dot_data last_node_id ] = ...
                    graph.print_dot(last_node_id, ...
                                    title );
                if strcmp(output_name, 'D1_data')
                    global oru_models;
                    oru_model = d_model;
                    oru_model.name = title;
                    oru_models = [ oru_models oru_model ];
                end
            end
            % perform contraction
            [ ~ ] = d_model.contract_all(contract_type, ...
                                              operation_type, ...
                                              output_name, graph);
            %'e4'
            if strcmp( contract_type, 'optimal' )
                cost = graph.get_optimal_path_cost();
            else
                % does not work on full contraction type
                cost = 0;
            end
        end
        function [graph] = schedule_dp(obj)
        % returns a tree of PLTFModel generated as a result of the
        % search for least memory consuming contraction sequence
        % with a dynamic programming approach
            output_dims = obj.get_contraction_dims();
            contraction_dims = obj.get_contraction_dims();
            graph = GTMGraph;
            process_nodes = [obj];
            processing_node = 1;
            % init graph.node_list
            graph.node_list = obj;
            graph=graph.clear_edges();
            while length(process_nodes) >= processing_node
                cur_node = process_nodes(processing_node);
                %cur_node = cur_node.update_cost_from_temp();
                contraction_dims = cur_node.get_current_contraction_dims();
                for udi = 1:length(contraction_dims)
                    new_node = cur_node.contract( contraction_dims(udi), ...
                                                  'mem_analysis', ...
                                                  '' );
                    % last operation does not have memory cost data
                    % is handled outside of pltf_iteration
                    if ~length(new_node.get_current_contraction_dims())
                        new_node.cost = 0;
                    end
                    % memoization
                    nnidx = graph.exists(new_node);
                    if nnidx
                        %['old node ' new_node.name]
                        graph = graph.update_node(cur_node, new_node, nnidx);
                    else
                        %['new node ' new_node.name]
                        graph = graph.append_node(cur_node, new_node);
                        process_nodes = [ process_nodes new_node ];
                    end
                end
                processing_node = processing_node + 1;
            end
        end
        function [newmodel ] = contract_all(obj, contract_type, ...
                                                     operation_type, ...
                                                     output_name, graph )
        % Performs all necessary contraction operations for the
        % model. If contract_type argument is equal to 'optimal'
        % then schedule_dp() is used to find the optimal (least
        % memory using) sequence and the optimal sequence is used
        % to contract all necessary dimensions. Otherwise
        % get_contraction_dims() is used to order contraction
        % operation which does not order dimensions. If
        % contract_type equals to 'full', no intermediate
        % contractions are performed, full tensor is calculated and
        % then contracted into the output tensor
        % output_name: name of the global data structure to store
        % the final result into, not used if operation type is not
        % 'compute'.
        %
        % operation_type argument may be 'compute' or
        % 'mem_analysis'. Normal operations are performed in
        % 'compute' (default), memory usage is reported in
        % 'mem_analysis' case.
        %
        % returns the model generated after contracting all
        % necessary dimension and the total extra memory required
        % by all temporary elements
            if nargin < 4
                output_name = '';
            end
            if nargin < 3
                operation_type = 'compute';
            end
            if nargin < 2
                contract_type = 'standard';
            end
            if strcmp(operation_type, 'compute') && ...
                    isempty(output_name)
                throw(MException('PLTFModel:ContractAllNoOutputName', ...
                                 ['output_name must be specified if ' ...
                                  'operation type is ''compute''' ]));
            end
            if strcmp( contract_type, 'optimal' )
                [contract_dims] = ...
                    obj.get_optimal_contraction_sequence_dims(graph);
                %for i=1:length(contract_dims)
                %    display(['optimal contracting ' ...
                %             char(contract_dims{i})]);
                %end
            elseif  ~strcmp( contract_type, 'full' )
                contract_dims = obj.get_contraction_dims();
                %for i=1:length(contract_dims)
                %    display(['contracting ' contract_dims(i).name]);
                %end
            end
            newmodel = obj;
            if strcmp( contract_type, 'full')
                [ newmodel ] = ...
                    obj.contract_full(operation_type, output_name);
                %['e5' contract_type]
            else
                for i = 1:length(contract_dims)
                    if i == length(contract_dims)
                        on = output_name;
                    else
                        on = '';
                    end
                    [ newmodel ]= ...
                        newmodel.contract(contract_dims(i), ...
                                          operation_type, ...
                                          on );
                end
            end
        end
        function [newmodel] = contract_full(obj, operation_type, ...
                                                      output_name)
        % generates a new full (temporary) tensor, multiplies all
        % latent tensors in to the full tensor and then
        % contracts full tensor over necessary indices and returns
        % newmodel with full_tensor and contracted result in global
        % data named 'output_name'
            % generate full tensor
            F = TFFactor;
            F.name = 'full_tensor';
            F.isTemp = 1;
            F.dims = obj.dims;    % full indices
            global F_size;
            F_size = F.get_element_size();
            global full_tensor_data;
            eval([ 'global ' output_name ]);
            if strcmp( operation_type, 'compute' )
                % generate global full_tensor_data
                sz = '';
                for adi = 1:length(obj.dims)
                    if adi ~= 1
                        sz = [sz ', '];
                    end
                    sz = [sz num2str(obj.dims(adi).cardinality) ];
                end
                eval( [ ' full_tensor_data = ones(' sz ');'] );
            else
                % in case of mem_analysis  make length of global data
                % greater than 0 for memory size computation
                full_tensor_data = 1;
            end
            if strcmp( operation_type, 'compute' )
                % access global data of all latent factors
                lfi = obj.latent_factor_indices;
                for lfii = 1:length(lfi)
                    eval(['global ' ...
                          obj.get_factor_data_name( obj.factors(lfi(lfii)) ) ...
                         ]);
                end
                % multiply all latent tensors, store result in data_F
                for lfii = 1:length(lfi)
                    % following tensors should be multiplied with data_F
                    eval([ 'full_tensor_data = bsxfun(@times, full_tensor_data, ' ...
                           obj.get_factor_data_name( ...
                               obj.factors(lfi(lfii)) ) ');' ]);
                end
                % contract necessary dimensions from full_tensor_data
                contract_dims = obj.get_contraction_dims();
                for cdi = 1:length(contract_dims)
                    if cdi == length(contract_dims)
                        eval( [ output_name [ ' = sum( full_tensor_data,' ...
                                            ' obj.get_dimension_index(' ...
                                            ' contract_dims(cdi)) ' ...
                                            ');' ] ] );
                    else
                        full_tensor_data = sum( full_tensor_data,        ...
                                                obj.get_dimension_index( ...
                                                    contract_dims(cdi)) ...
                                                );
                    end
                end
            end
            newmodel = obj;
            newmodel.factors = [ obj.observed_factor F ];
        end
        function [newmodel] = contract(obj, dim, operation_type, ...
                                                 output_name)
        % returns a new PLTFModel generated by contracting obj with
        % dim which may add new temporary factors and mem_delta
        % integer value.
        % dim: TFDimension or char array or cell with the name of
        % the dimension
        % operation_type: if equals to 'compute' contraction is
        % calculated. if equals to 'mem_analysis' data elements are
        % not created.
        % output_name: if has length > 0 do not generate temporary
        % factor but use global data storage named 'output
        % name'.
        %[ 'contract START dim length ' num2str(length(dim))]
            if length(dim) == 0
                throw(MException('PLTFModel:NoContractionDimensionSpecified', ...
                                 ['must specify contraction ' ...
                                  'dimension']));
            end
            if isa(dim, 'TFDimension')
                dim = dim.name;
            elseif isa(dim, 'cell')
                dim = char(dim{1});
            elseif ~isa(dim, 'char')
                display(['ERROR: unsupported dim type ' class(dim) ...
                         'was expecting TFDimension, cell or char ' ...
                         'array']);
                return
            end
            newmodel = obj;
            newmodel.name = [obj.name '_' dim];
            % remove dim from the new model's factors'
            contracted_factor_inds = [];
            for f = 1:length(newmodel.factors)
                if ~newmodel.factors(f).isObserved
                    ind = ...
                        newmodel.factors(f).got_dimension(char(dim));
                    if ind ~= 0
                        % remove this dimension from this factor
                        newmodel.factors(f).dims(ind) = [];
                        contracted_factor_inds = ...
                            [ contracted_factor_inds f ];
                    end
                end
            end
            % add a temporary factor including dimensions of
            % contracted factors other than contracted dimension
            tmp=TFFactor;
            tmp.isTemp = 1;
            tmp.name = 'tmp';
            names={};
            for cfii = 1:length(contracted_factor_inds)
                % for each dimension of the contracted factor
                for cfi_dim = 1:length(newmodel.factors(contracted_factor_inds(cfii)).dims)
                    found=0;
                    for ti = 1:length(tmp.dims)
                        if tmp.dims(ti) == ...
                                newmodel.factors(contracted_factor_inds(cfii)).dims(cfi_dim)
                            found=1;
                            break;
                        end
                    end
                    if found == 0
                        tmp.dims = [tmp.dims ...
                                    newmodel.factors(contracted_factor_inds(cfii)) ...
                                    .dims(cfi_dim)];
                        names=[names ...
                              newmodel.factors(contracted_factor_inds(cfii)).dims(cfi_dim).name];
                        %display(['added from factor index' ...
                        %         contracted_factor_inds(cfii)])
                        %display(['added from factor' newmodel.factors(contracted_factor_inds(cfii)).name])
                        %display(['addd dim' char(newmodel.factors(contracted_factor_inds(cfii)).dims(cfi_dim).name)])
                    end
                end
            end
            names=unique(names);
            for d = 1:length(names)
                tmp.name = [tmp.name '_' char(names(d))];
                %tmp.name
            end
            tmp.name = [tmp.name '_minus_' dim];
            % calculate output data
            if isempty(output_name)
                % if output if not given store in global variable
                % with tmp.coded_name
                on = obj.get_factor_data_name(tmp);
                %eval( [ 'global ' on ';' ])
           else
                on = output_name;
                % TODO: make sure output has correct dimensions
                % eval( [ 'global ' on  ';'] );
                % tmpsz = size(tmp.get_data_name());
            end
            %['SELECTED on ' on  ' tmp.name ' tmp.name ' operation_type ' ...
            % operation_type]
            if strcmp( operation_type, 'compute' )
                eval( [ 'global ' on  ';'] );
                %[ 'on0: ' on '' ]
                %eval([ 'on_len0 = length( ' on ' )' ]);
                if length(contracted_factor_inds) == 1
                    %'sdfa111'
                    % no multiplication
                    eval( [ 'global ' ...
                            obj.get_factor_data_name( obj.factors(contracted_factor_inds(1)) ) ...
                            ';'] );
                    %['aa :' obj.get_factor_data_name( ...
                    %    obj.factors(contracted_factor_inds(1)) ) ]
                    %['aalen :']
                    eval( [ 'length( ' obj.get_factor_data_name( ...
                        obj.factors(contracted_factor_inds(1)) ) ');' ])
                    %[ obj.get_factor_data_name( ...
                    %    obj.factors(contracted_factor_inds(1)) ) ...
                    %  ' -> ' ...
                    %  on ]
                    eval( [ on ' = ' ...
                            obj.get_factor_data_name( obj.factors(contracted_factor_inds(1)) ) ...
                            ';'] );
                else
                    %'sdfa222'
                    % multiply first two into tmp data
                    eval( [ 'global' ...
                            ' ' obj.get_factor_data_name( obj.factors(contracted_factor_inds(1)) ) ...
                            ' ' obj.get_factor_data_name( obj.factors(contracted_factor_inds(2)) ) ...
                            ';'] );
                    %[ obj.get_factor_data_name( ...
                    %    obj.factors(contracted_factor_inds(1)) ) ...
                    %  ' * ' ...
                    %  obj.get_factor_data_name( ...
                    %      obj.factors(contracted_factor_inds(2)) ) ...
                    %  ' -> ' ...
                    %  on ]
                    eval( [ on ' = bsxfun (@times, ' ...
                            obj.get_factor_data_name( obj.factors(contracted_factor_inds(1)) ) ', '...
                            obj.get_factor_data_name( obj.factors(contracted_factor_inds(2)) ) ');' ...
                          ] );
                    % multiply tmp data with other factors
                    for cfii = 3:length(contracted_factor_inds)
                        eval( [ 'global '...
                                obj.get_factor_data_name( obj.factors(contracted_factor_inds(cfii)) ) ...
                                ';'] );
                        eval( [ on ' = bsxfun (@times, ' ...
                                on ','...
                                obj.get_factor_data_name( obj.factors(contracted_factor_inds(cfii)) ) ...
                                ');' ] );
                    end
                end
                % sum contraction dimensions on tmp data
                con_dim_index = obj.get_dimension_index(dim);
                eval( [ on ' = sum( ' ...
                        on ', ' ...
                        num2str(con_dim_index) ');'] );
            else
                % in case of mem_analysis  make length of global data
                % greater than 0 for memory size computation
                % schedule_dp must not perform memory size calculation
                %stack = dbstack();
                %if ~strcmp(stack(2).name, ...
                %           'PLTFModel.schedule_dp')
                %    eval([ on ' = 1 ;' ]);
                %end
            end
            if isempty(output_name)
                newmodel.factors = [newmodel.factors tmp];
            end
            % remove contracted factors
            % other dimensions live within the tmp factor
            removed_num=0; % removal breaks loop index
            for cfii = 1:length(contracted_factor_inds)
                newmodel.factors(contracted_factor_inds(cfii) ...
                                 - removed_num) = [];
                removed_num = removed_num + 1;
            end
            if isempty(output_name)
                newmodel = newmodel.update_cost_from_temp();
            end
        end
        function [ocs_dims] = get_optimal_contraction_sequence_dims(obj, ...
                                                              graph)
        % Runs schedule_dp function to generate graph with least
        % memory using contraction sequence information in it. Then
        % searches GTMGraph.optimal_edges for the optimal path and
        % returns a cell list of contraction dimension names.
            global ocs_cache;
            found = false;
            for o = 1:length(ocs_cache)
                if ocs_cache(o).model == obj
                    found=true;
                    break
                end
            end
            if found
                %display('cache hit')
                %display([ 'ocs dims' ])
                ocs_dims = ocs_cache(o).ocs_dims;
                %for a =1:length(ocs_dims)
                %    ocs_dims{a}
                %end
                return
            %else
            %    display('cache miss')
            end
            %graph = obj.schedule_dp();
            [ocs_dims] = graph.optimal_sequence_from_graph();
            %cost
            %obj.cost = obj.cost + cost;
            %display([ 'cache store' ])
            %for a =1:length(ocs_dims)
            %    ocs_dims{a}
            %end
            ocs_cache = [ ocs_cache TFOCSCache(obj, ocs_dims) ];
        end
        function [obj] = update_cost_from_temp(obj)
            obj.cost = 0;
            lfi = obj.latent_factor_indices();
            for fi = 1:length(lfi)
                if obj.factors(lfi(fi)).isTemp
                    obj.factors(lfi(fi)).name;
                    obj.cost = obj.cost + ...
                        obj.factors(lfi(fi)).get_element_size();
                end
            end
            %['updatecost ' obj.name ' ' num2str(obj.cost)]
        end
        function [obj] = update_cost_from_latent(obj)
            obj.cost = 0;
            lfi=obj.latent_factor_indices();
            for fi = 1:length(lfi)
                obj.cost = obj.cost + ...
                    obj.factors(lfi(fi)).get_element_size();
            end
        end
        function [dn fn all_edges] = print_ubigraph(obj)
        % returns a string to be used by fgplot
        % add dimension nodes
            dn = [ '[ ''' ];
            for i =1:length(obj.dims)
                if i ~= 1
                    dn = [ dn ''',''' ];
                end
                dn = [ dn obj.dims(i).name ];
            end
            dn = [ dn ''' ] ' ];
            % add factor nodes
            fn = [ '[ ''' ];
            for i =1:length(obj.factors)
                if i ~= 1
                    fn = [ fn ''',''' ];
                end
                fn = [ fn obj.factors(i).name ];
            end
            fn = [ fn ''' ] ' ];
            % add edges
            all_edges=['[ ' ];
            for d = 1:length(obj.dims)
                if d ~= 1
1000                     all_edges = [ all_edges ' , ' ];
1001                 end
1002
1003                 edges=['[ ' ];
1004
1005                 % include this dimension if a factor uses it
1006                 for f = 1:length(obj.factors)
1007                     for fd = 1:length(obj.factors(f).dims)
1008                         if obj.factors(f).dims(fd) == obj.dims(d)
1009                             if length(edges) ~= 2
1010                                 edges = [ edges ''',''' ];
1011                             else
1012                                 edges = [ edges '''' ];
1013                             end
1014                             edges = [ edges obj.factors(f).name ];
1015                         end
1016                     end
1017                 end
1018
1019                 all_edges = [ all_edges edges ''' ]' ];
1020             end
1021             all_edges = [ all_edges ' ]' ];
1022         end
1023
1024
1025
1026
1027         function [size] = get_element_size(obj)
1028         % returns number of elements for this model
1029             size=0;
1030             for f = 1:length(obj.factors)
1031                 % if obj.factors(f).isObserved == 0
1032                 size = size + ...
1033                        obj.factors(f).get_element_size();
1034                 %end
1035             end
1036         end
1037
1038
1039
1040
1041         function [card] = get_index_card(obj, index_char)
1042         % returns cardinality of a given name of a dimension
1043             for d = 1:length(obj.dims)
1044                 if obj.dims(d).name == index_char
1045                     card = obj.dims(d).cardinality;
1046                     break
1047                 end
1048             end
1049         end
1050
1051
1052
1053
1054         function [factor] = get_first_non_observed_factor(obj)
1055         % returns first non observed factor index, used to return
1056         % index of the output factor when all latent factors are
1057         % contracted out. in this case only output (observed) and a
1058         % single temporary non-observed factors should be present
1059         % in the model (ie fully contracted model).
1060             for f = 1:length(obj.factors)
1061                 if obj.factors(f).isObserved == 0
1062                     factor = obj.factors(f);
1063                     return
1064                 end
1065             end
1066         end
1067
1068
1069
1070
1071         function [ind] = get_first_non_observed_factor_index(obj)
1072         % returns first non observed factor index, used to return
1073         % index of the output factor
1074             for f = 1:length(obj.factors)
1075                 if obj.factors(f).isObserved == 0
1076                     ind = f;
1077                     return
1078                 end
1079             end
1080         end
1081
1082
1083
1084
1085         function [ind] = find_cell_char(obj, chars)
1086         % returns index of a given char array in object's dimension array
1087             for ind=1:length(obj.dims)
1088                 if obj.dims(ind).name == chars
1089                     return
1090                 end
1091             end
1092             ind=0;
1093         end
1094
1095
1096
1097
1098        function [r] = get_dimension_index(obj, dim)
1099         % returns index of dimension dim in obj.dims if obj
1100         % contains TFDimension (or char) dim returns 0 otherwise
1101
1102             r=0;
1103             for d = 1:length(obj.dims)
1104                 if obj.dims(d) == dim
1105                     r=d;
1106                     break;
1107                 end
1108             end
1109        end
1110
1111
1112
1113
1114        function [ordered_index_chars] = order_dims(obj, ...
1115                                                     dims_array)
1116             % order given cell of dimension names according to
1117             % factor.dims order
1118
1119             tmp=cell(length(dims_array), 3);
1120
1121             tmp(:,1) = dims_array;
1122             for i = 1:length(dims_array)
1123                 tmp{i,2} = obj.get_index_card(char(dims_array(i)));
1124                 tmp{i,3} = obj.find_cell_char(char(dims_array(i))); % order of the index
1125                                                                     % in the model
1126             end
1127
1128             tmp=sortrows(tmp,3); % sort by the order of the model indices
1129             ordered_index_chars=tmp(:,1)';
1130         end
1131
1132
1133
1134
1135         function [alldims] = get_all_used_dims(obj)
1136         % returns dimensions in obj.dims which are used by model
1137         % factors. Models used by GCTF models may have dims listed
1138         % in obj.dims which are not used by any one of the factors
1139             alldims = [];
1140             for di = 1:length(obj.dims)
1141                 found = false;
1142                 for fi = 1:length(obj.factors)
1143                     if obj.factors(fi).got_dimension(obj.dims(di))
1144                         found = true;
1145                         break;
1146                     end
1147                 end
1148                 if found
1149                     alldims = [ alldims obj.dims(di) ];
1150                 end
1151             end
1152         end
1153
1154
1155
1156         function [contract_dims] = get_contraction_dims(obj)
1157         % returns cell of dimensions which must be contracted to
1158         % calculate output factor(s)
1159
1160             output_chars = {};
1161             for f=1:length(obj.factors)
1162                 if obj.factors(f).isObserved
1163
1164                     % for each dimension of this factor
1165                     for i=1:length(obj.factors(f).dims)
1166                         output_chars = [output_chars ...
1167                                         obj.factors(f).dims(i).name];
1168                     end
1169
1170                 end
1171             end
1172
1173             % contraction dimensions: alldims - output_dims
1174             % alldims was obj.dims but now it is not due to GCTF
1175             % usage which may cause obj.dims to include dims not
1176             % included in the model, now we must calculate alldims
1177             alldims = obj.get_all_used_dims();
1178
1179             contract_dims={};
1180             for d_a = 1:length(alldims)
1181                 found=0;
1182                 for d_o = 1:length(output_chars)
1183                     if alldims(d_a) == char(output_chars(d_o))
1184                         found=1;
1185                         break
1186                     end
1187                 end
1188
1189                 if found == 0
1190                     contract_dims = [contract_dims alldims(d_a)];
1191                     %['add '  alldims(d_a).name]
1192                 end
1193             end
1194
1195             %['return ' contract_dims.name]
1196             %contract_dims = obj.order_dims(unique(contract_dims));
1197         end
1198
1199
1200
1201
1202         function [contract_dims] = get_current_contraction_dims(obj)
1203         % returns cell of TFDimensions which must be contracted to
1204         % calculate output factor(s) by using current factors to
1205         % calculate all dimension not model.dims. (model.dims is always
1206         % fixed to maximum possible dimension list.)
1207
1208             output_chars = {};
1209             for f=1:length(obj.factors)
1210                 if obj.factors(f).isObserved
1211
1212                     % for each dimension of this factor
1213                     for i=1:length(obj.factors(f).dims)
1214                         output_chars = [output_chars ...
1215                                         obj.factors(f).dims(i).name];
1216                     end
1217
1218                 end
1219             end
1220
1221             % contraction dimensions: alldims - output_dims
1222             alldims={};
1223             for f = 1:length(obj.factors)
1224                 for d = 1:length(obj.factors(f).dims)
1225                     found = 0;
1226                     n=obj.factors(f).dims(d).name;
1227                     for i=1:length(alldims)
1228                         if char(alldims(i)) == n
1229                             found = 1;
1230                             break
1231                         end
1232                     end
1233
1234                     if ~found
1235                         alldims = [alldims n];
1236                     end
1237                 end
1238             end
1239
1240             contract_dims={};
1241             for d_a = 1:length(alldims)
1242                 found=0;
1243                 for d_o = 1:length(output_chars)
1244                     if char(alldims(d_a)) == char(output_chars(d_o))
1245                         found=1;
1246                         break
1247                     end
1248                 end
1249
1250                 if found == 0
1251                     contract_dims = [contract_dims alldims(d_a)];
1252                     %['add '  alldims(d_a).name]
1253                 end
1254             end
1255
1256             %['return ' contract_dims.name]
1257             %contract_dims = obj.order_dims(unique(contract_dims));
1258         end
1259
1260
1261
1262
1263         function [factor_inds] = latent_factor_indices(obj)
1264             factor_inds=[];
1265             for f=1:length(obj.factors)
1266                 if obj.factors(f).isLatent
1267                     factor_inds = [ factor_inds f ];
1268                 end
1269             end
1270         end
1271
1272
1273
1274
1275         function [factors] = latent_factors(obj)
1276             factors=[];
1277             for f=1:length(obj.factors)
1278                 if obj.factors(f).isLatent
1279                     factors = [ factors obj.factors(f) ];
1280                 end
1281             end
1282         end
1283
1284
1285
1286
1287         function [factor_ind] = observed_factor_index(obj)
1288             factor_ind=0;
1289             for f=1:length(obj.factors)
1290                 if obj.factors(f).isObserved
1291                     factor_ind = f;
1292                     return
1293                 end
1294             end
1295         end
1296
1297
1298
1299
1300         function [factor] = observed_factor(obj)
1301         % returns first observed factor (useful for PLTF operations)
1302             for f=1:length(obj.factors)
1303                 if obj.factors(f).isObserved
1304                     factor = obj.factors(f);
1305                     return
1306                 end
1307             end
1308         end
1309
1310
1311
1312
1313         function [factors] = observed_factors(obj)
1314             factors=[];
1315             for f=1:length(obj.factors)
1316                 if obj.factors(f).isObserved
1317                     factors = [ factors obj.factors(f) ];
1318                 end
1319             end
1320         end
1321
1322
1323
1324
1325         function [factors] = input_factors(obj)
1326             factors=[];
1327             for f=1:length(obj.factors)
1328                 if obj.factors(f).isInput
1329                     factors = [ factors obj.factors(f) ];
1330                 end
1331             end
1332         end
1333
1334
1335
1336
1337         function [factors] = temp_factors(obj)
1338             factors=[];
1339             for f=1:length(obj.factors)
1340                 if obj.factors(f).isTemp
1341                     factors = [ factors obj.factors(f) ];
1342                 end
1343             end
1344         end
1345
1346
1347
1348
1349         function [index] = get_factor_index(obj, factor)
1350         % returns index of a factor in factor list
1351         % if factor does not exist returns 0
1352             index = 0;
1353             for f = 1:length(obj.factors)
1354                 if factor == obj.factor(f)
1355                     index = f;
1356                     break;
1357                 end
1358             end
1359         end
1360
1361
1362
1363
1364         function [name] = get_factor_data_name(obj, index)
1365         % returns global data name of the factor at index of
1366         % factors TFFactor array. index may be an TFFactor instance.
1367         %
1368         % To preserve model elements' data, their naming structure
1369         % is different than temporary factors. Model data elements
1370         % use TFFactor.get_data_name whereas temporary elements use
1371         % PLTFModel.get_coded_factor_name. This it is possible to
1372         % re-use memory structures with same dimensions
1373             if isa(index, 'TFFactor')
1374                 factor = index;
1375             elseif isnumeric(index)
1376                 factor = obj.factors(index);
1377             end
1378
1379             if factor.isTemp
1380                 name = obj.get_coded_factor_name(factor);
1381             else
1382                 % assume we have model element
1383                 name = factor.get_data_name();
1384             end
1385         end
1386
1387
1388         function [code_name] = get_coded_factor_name(obj, index)
1389         % returns coded name of the factor at index, used
1390         % index may be a factor, in which case factor does not need
1391         % to exist in obj.factors
1392         % internally for detecting data using same dimensions
1393         % used with temporary factors in order to re-use same
1394         % dimension data structures
1395
1396             if isnumeric(index)
1397                 dims = obj.factors(index).dims;
1398             elseif isa(index, 'TFFactor')
1399                 dims = index.dims;
1400             end
1401
1402             code_name = ['factor_' ...
1403                 char(obj.order_dims(TFDimensionList2cell(dims)))'];
1404         end
1405
1406
1407
1408         function [] = rand_init_latent_factors(obj, type, imax)
1409
1410             if ~strcmp(type, 'all') && ~strcmp(type, 'nonClamped')
1411                 throw(MException('PLTFModel:WrongInitType', ...
1412                                  ['Supported init type values: all, ' ...
1413                                   'nonClamped']));
1414             end
1415
1416             for fi=1:length(obj.latent_factor_indices)
1417
1418                 if strcmp(type, 'all') || ...
1419                         (strcmp(type, 'nonClamped') && ...
1420                           obj.factors(fi).isInput == 0)
1421
1422                     data_name = [obj.get_factor_data_name(fi)];
1423
1424                     if nargin==2
1425                         obj.factors(fi).rand_init(obj.dims, 100, data_name);
1426                     else
1427                         obj.factors(fi).rand_init(obj.dims, imax, data_name);
1428                     end
1429
1430                 end
1431             end
1432
1433         end
1434
1435
1436
1437
1438         function [r] = eq(a,b)
1439             r = false;
1440
1441             % mark matched b factors
1442             % if there are any unmarked -> inequal
1443             % problematic case:
1444             % a.factors (ip, jpi) , b.factors (ip, pi)
1445             % b==a matches all b objects with a.factors(1)
1446             % but a~=b !
1447
1448             b_marks = zeros(size(b.factors));
1449
1450             if length(a.factors) == length(b.factors)
1451                 for f_a = 1:length(a.factors)
1452                     found = 0;
1453                     for f_b = 1:length(b.factors)
1454                         if a.factors(f_a) == b.factors(f_b) && ...
1455                                 b_marks(f_b) == 0
1456                             found = 1;
1457                             b_marks(f_b) = 1;
1458                             break
1459                         end
1460                     end
1461
1462                     if found == 0
1463                         return
1464                     end
1465                 end
1466
1467                 r = true;
1468             end
1469         end
1470
1471
1472
1473
1474         function [] = full_pltf_mem_analysis(obj)
1475             obj.pltf(1, 'full', 'mem_analysis');
1476         end
1477
1478
1479
1480
1481         function [] = optimal_pltf_mem_analysis(obj)
1482             obj.pltf(1, 'optimal', 'mem_analysis');
1483         end
1484
1485
1486
1487
1488     end
1489
1490
1491
1492
1493 end