Description of TFModel
TFModel
PURPOSE
Represents data required to describe a tensor factorization model
SYNOPSIS
This is a script file.
DESCRIPTION
 Represents data required to describe a tensor factorization model
   A model is represented with its name and factors array of
   TFFactor objects. dims array of TFDimension objects define
   dimensions used by this model. Dimensions are transfered to C++
   in the order defined in dims array. See examples below for a
   full model description.
   Examples:
   dim_i = TFDimension('name', 'i', 'cardinality', 5);
   dim_j = TFDimension('cardinality', 6, 'name', 'j');
   dim_k = TFDimension('cardinality', 7, 'name', 'k');
   dim_r = TFDimension('cardinality', 10, 'name', 'r');
   p_A=TFFactor('name', 'p_A', 'type', 'latent', 'dims', [dim_i dim_r]);
   p_B=TFFactor('name', 'p_B', 'type', 'latent', 'dims', [dim_j dim_r]);
   p_C=TFFactor('name', 'p_C', 'type', 'latent', 'dims', [dim_k dim_r]);
   parafac_model = TFModel('name', 'Parafac', 'factors', [p_A p_B p_C X], 'dims', [dim_i dim_j dim_k dim_r]);
   parafac_model.rand_init_latent_factors('all');
   See also TFDimension, TFFactor
CROSS-REFERENCE INFORMATION
This function calls:
TFDimension Represents a single dimension
TFFactor Represents a PLTF factor
TFGraph Represents a graph of TFModel objects.
TFModel Represents data required to describe a tensor factorization model
TFOCSCache Represents cached search results for optimal contraction sequence search operation
This function is called by:
TFGraph Represents a graph of TFModel objects.
TFModel Represents data required to describe a tensor factorization model
TFOCSCache Represents cached search results for optimal contraction sequence search operation
SUBFUNCTIONS
function obj = TFModel(varargin)
function [] = pltf(obj, iternum, contract_type, operation_type)
function [ kl extra_mem ] = pltf_iteration(obj,
function [extra_mem] = delta(obj, alpha, output_name,
function [graph] = schedule_dp(obj, operation_type)
function [newmodel] = uncontract(obj, orig_model, dim)
function [newmodel extra_mem] = contract_all(obj, contract_type, operation_type)
function [newmodel extra_mem] = contract_full(obj, operation_type)
function [newmodel extra_mem] = contract(obj, dim, operation_type)
function [ocs_dims] = get_optimal_contraction_sequence_dims(obj,
function [obj] = update_cost_from_latent(obj)
function [dn fn all_edges] = print_ubigraph(obj)
function [size] = get_element_size(obj)
function [card] = get_index_card(obj, index_char)
function [factor] = get_first_non_observed_factor(obj)
function [ind] = get_first_non_observed_factor_index(obj)
function [ind] = find_cell_char(obj, chars)
function [r] = get_dimension_index(obj, dim)
function [ordered_index_chars] = order_dims(obj,
function [contract_dims] = get_contraction_dims(obj)
function [contract_dims] = get_current_contraction_dims(obj)
function [factor_inds] = latent_factor_indices(obj)
function [factors] = latent_factors(obj)
function [factor_ind] = observed_factor_index(obj)
function [factor] = observed_factor(obj)
function [factors] = observed_factors(obj)
function [factors] = input_factors(obj)
function [factors] = temp_factors(obj)
function [] = rand_init_latent_factors(obj, type, imax)
function [r] = eq(a,b)
function [uncontraction_dims] = get_uncontraction_dims(obj)
SOURCE CODE
% Represents data required to describe a tensor factorization model
%
%   A model is represented with its name and factors array of
%   TFFactor objects. dims array of TFDimension objects define
%   dimensions used by this model. Dimensions are transfered to C++
%   in the order defined in dims array. See examples below for a
%   full model description.
%
%   Examples:
%
%   dim_i = TFDimension('name', 'i', 'cardinality', 5);
%   dim_j = TFDimension('cardinality', 6, 'name', 'j');
%   dim_k = TFDimension('cardinality', 7, 'name', 'k');
%   dim_r = TFDimension('cardinality', 10, 'name', 'r');
%
%   p_A=TFFactor('name', 'p_A', 'type', 'latent', 'dims', [dim_i dim_r]);
%   p_B=TFFactor('name', 'p_B', 'type', 'latent', 'dims', [dim_j dim_r]);
%   p_C=TFFactor('name', 'p_C', 'type', 'latent', 'dims', [dim_k dim_r]);
%
%   parafac_model = TFModel('name', 'Parafac', 'factors', [p_A p_B p_C X], 'dims', [dim_i dim_j dim_k dim_r]);
%
%   parafac_model.rand_init_latent_factors('all');
%
%   See also TFDimension, TFFactor
classdef TFModel
    properties
        name='';          % name of the model
        factors=TFFactor; % array of TFFactor
        dims=TFDimension; % array of TFDimension used by factors defines
                          % order of dimensions on memory
        cost=0;
    end
    methods
        function obj = TFModel(varargin)
            p = inputParser;
            addParamValue(p, 'name', '', @isstr);
            addParamValue(p, 'factors', [], @isvector);
            addParamValue(p, 'dims', [], @isvector);
            parse(p,varargin{:});
            % check if all dims elements are TFDimension objects
            for i = 1:length(p.Results.dims)
                if ~isa(p.Results.dims(i), 'TFDimension')
                    err = MException( ...
                        ['TFModel:DimensionNotTFDimension'], ...
                        ['Dimensions of TFModel must be ' ...
                         'TFDimension objects']);
                    throw(err);
                end
            end
            obj.dims = p.Results.dims;
            % check if all factors are TFFactor objects
            for i = 1:length(p.Results.factors)
                if ~isa(p.Results.factors(i), 'TFFactor')
                    err = MException( ...
                        ['TFModel:FactorsNotTFFactor'], ...
                        ['Factors of TFModel must be ' ...
                         'TFFactor objects']);
                    throw(err);
                end
            end
            obj.factors = p.Results.factors;
            obj.name = p.Results.name;
        end
        function [] = pltf(obj, iternum, contract_type, operation_type)
        % performs PLTF update operations on the model
        % returns estimated TFFactor (\hat(X))
        %
        % iternum: number of iterations
        %
        % contract_type: if equals to 'optimal', contractions are
        % performed in least memory using sequence defines order of
        % contraction operations, if equals to 'full', full tensor
        % is used for contraction operations instead of generating
        % temporary factors.
        %
        % operation_type: if equals to 'compute' normal contraction
        % operations are performed. if equals to 'mem_analysis'
        % operation are not performed but memory requirement is
        % calculated and reported.
            if nargin == 2
                contract_type = '';
            end
            if nargin < 4
                operation_type = 'compute';
            end
            % init optimal model cache
            global ocs_cache;
            ocs_cache = [];
            % initalize data_mem with memory requirements of the
            % model elements
            data_mem = obj.get_element_size();
            hat_X = obj.observed_factor;
            hat_X.name = 'hat_X';
            % hat_X requires extra memory
            data_mem = data_mem + hat_X.get_element_size();
            if strcmp( operation_type, 'compute' )
                eval( [ 'global ' obj.observed_factor.get_data_name() ...
                        ';' ] );
                global hat_X_data;
                hat_X.rand_init(obj.dims, 100);
            end
            mask = obj.observed_factor;
            mask.name = 'mask';
            % mask requires extra memory
            data_mem = data_mem + mask.get_element_size();
            if strcmp( operation_type, 'compute' )
                global mask_data;
                mask_data = ones(size(hat_X_data));
                KL=zeros(1,iternum);
                for iter = 1:iternum
                    display(['iteration' char(9) num2str(iter)]);
                    [ kl extra_mem ] = obj.pltf_iteration(contract_type, ...
                                                          hat_X, ...
                                                          mask, ...
                                                          operation_type);
                    KL(iter) = kl;
                end
                display(['KL divergence over iterations: ']);
                display(KL);
                plot(KL);
                title('KL divergence over iterations');
                xlabel('iteration number');
                ylabel('KL divergence');
            elseif strcmp( operation_type, 'mem_analysis' )
                [ kl extra_mem ] = obj.pltf_iteration(contract_type, hat_X, ...
                                                      mask, ...
                                                      operation_type);
            end
            data_mem = data_mem + extra_mem;
            display([char(10) ...
                     'data elements required: ' num2str(data_mem) ...
                     char(10) ...
                     ['memory size with (8 byte) double precision: ' ...
                      num2str(8 * data_mem / 1000 / 1000) ' MB' ] ] );
        end
        function [ kl extra_mem ] = pltf_iteration(obj, ...
                                                  contract_type, ...
                                                  hat_X, mask, ...
                                                  operation_type)
            % helper function for the pltf inner loop
            % operation_type: 'compute' if actual computation is
            % requested, 'mem_analysis' if only memory usage
            % computation is requested
            %
            % returns KL divergence value calculated at the end of
            % the operations. extra_mem is incremented with
            % temporary data usage requirements
            extra_mem = 0;
            for alpha=1:length(obj.latent_factor_indices)
                % access global data
                eval( [ 'global ' obj.observed_factor.get_data_name() ...
                        ';' ] );
                global hat_X_data mask_data;
                X_name = obj.factors(obj.observed_factor_index) ...
                         .get_data_name();
                eval(['global ' X_name ';']);
                Z_alpha_name = ...
                    obj.factors(alpha).get_data_name();
                eval( [ 'global ' Z_alpha_name ';' ] );
                % recalculate hat_X
                newmodel = obj;
                %if iter==1 && alpha==1
                    %g = newmodel.schedule_dp(operation_type);
                    %system([ 'rm /tmp/img.eps; echo '' ' g.print_dot  [' '' |' ...
                    %                    ' dot -o /tmp/img.eps; ' ...
                    %                    ' display  /tmp/img.eps ' ...
                    %                    ' ' ] ] );
                %end
                % perform contraction
                [ newmodel e_m ] = ...
                    newmodel.contract_all(contract_type, ...
                                          operation_type);
                extra_mem = extra_mem + e_m;
                % store result in hat_X_data
                result_name = ...
                    newmodel.get_first_non_observed_factor() ...
                    .get_data_name();
                eval(['global ' result_name ';'] );
                eval(['hat_X_data = ' result_name ';' ] );
                % store X / hat_X in hat_X data
                if strcmp( operation_type, 'compute' )
                    eval( [ 'hat_X_data  =  ' ...
                            X_name ...
                            ' ./ ' ...
                            ' hat_X_data ;' ] );
                end
                % generate D1
                [ e_m ] = obj.delta(alpha, 'D1_data', ...
                                    contract_type, ...
                                    operation_type, ...
                                    hat_X);
                extra_mem = extra_mem + e_m;
                % generate D2
                [ e_m ] = obj.delta(alpha, 'D2_data', ...
                                    contract_type, ...
                                    operation_type, ...
                                    mask);
                extra_mem = extra_mem + e_m;
                % update Z_alpha
                if strcmp( operation_type, 'compute' )
                    global D1_data D2_data;
                    eval( [ Z_alpha_name '=' Z_alpha_name ' .* ' ...
                            'D1_data'                     ' ./ ' ...
                            'D2_data ;' ] );
                end
            end
            if strcmp( operation_type, 'compute' )
                % calculate KL divergence
                eval ( [ 'kl = sum(sum(sum( (hat_X_data .* ' X_name ') .* ' ...
                         ' (log( (hat_X_data .* ' X_name ') ) - ' ...
                         'log(' X_name ...
                         ') ) - (hat_X_data .* ' X_name ')' ...
                         '+ ' X_name ...
                         ')));' ]);
            else
                kl = 0;
            end
        end
        function [extra_mem] = delta(obj, alpha, output_name, ...
                                     contract_type, operation_type, ...
                                     A)
        % PLTF delta function implementation
        % alpha: index of latent factor in TFModel.factors array
        % which will be updated
        % name: unique name used as the name of calculated delta
        % factor data
        % contract_type: see description in pltf function
        % A: operand element of delta function assumed all ones if
        % not given
        %
        % returns extra_mem required by temporary tensor usage
            extra_mem = 0;
            % create new model for delta operation
            d_model = obj;
            % remove observed factor
            d_model.factors(d_model.observed_factor_index) = [];
            % add Z_alpha as new observed factor
            d_model.factors(alpha).isLatent = 0;
            d_model.factors(alpha).isObserved= 1;
            % if given, add A as a new latent factor
            if nargin == 6
                A.isLatent = 1;
                A.isObserved = 0;
                d_model.factors = [d_model.factors A];
            end
            %g = d_model.schedule_dp(operation_type);
            %system( [ 'rm /tmp/img.eps; echo '' ' g.print_dot  [' '' |' ...
            %                    ' dot -o /tmp/img.eps ;  display  /tmp/img.eps; ' ] ] );
            % perform contraction
            [ d_model e_m ] = d_model.contract_all(contract_type, ...
                                                   operation_type);
            extra_mem = extra_mem + e_m;
            if strcmp( operation_type, 'compute' )
                eval( [ 'global ' output_name ';'] );
                eval( [ 'global ' ...
                        d_model.get_first_non_observed_factor().get_data_name() ';'...
                      ] );
                eval( [ output_name '=' ...
                        d_model.get_first_non_observed_factor().get_data_name() ...
                        ';' ]);
            end
        end
        function [graph] = schedule_dp(obj, operation_type)
        % returns a tree of TFModel generated as a result of the
        % search for least memory consuming contraction sequence
        % with a dynamic programming approach
            output_dims = obj.get_contraction_dims();
            contraction_dims = obj.get_contraction_dims();
            % generate final state of contraction operation to be
            % used as the initial state of dp search
            end_node = obj.contract_all('standard', ...  % must not be optimal or infinite loop!
                                        operation_type);
            graph = TFGraph;
            process_nodes = [end_node];
            processing_node = 1;
            while length(process_nodes) >= processing_node
                cur_node = process_nodes(processing_node);
                cur_node = cur_node.update_cost_from_latent();
                % init graph.node_list
                if length(graph.node_list) == 0
                    graph.node_list = [cur_node];
                    graph=graph.clear_edges();
                end
                uncontraction_dims = cur_node.get_uncontraction_dims();
                for udi = 1:length(uncontraction_dims)
                    new_node = cur_node.uncontract(obj, ...
                                                   uncontraction_dims(udi));
                    new_node = new_node.update_cost_from_latent();
                    % memoization
                    nnidx = graph.exists(new_node);
                    if nnidx
                        graph = graph.update_node(cur_node, new_node, nnidx);
                    else
                        graph = graph.append_node(cur_node, new_node);
                        process_nodes = [ process_nodes new_node ];
                    end
                end
                processing_node = processing_node + 1;
            end
        end
        function [newmodel] = uncontract(obj, orig_model, dim)
        % returns a new TFModel generated by adding given
        % TFDimension object dim to the model.
        % dim: TFDimension object to uncontract
        % orig_model: provides original non-contracted model data
            newmodel = obj;
            newmodel.name = [ newmodel.name  ...
                              '_uncontract_' dim.name ];
            uncontract_dims = obj.get_uncontraction_dims();
            other_dims = []; % already contracted dimensions
            for i=1:length(uncontract_dims)
                if uncontract_dims(i) ~= dim
                    other_dims = [ other_dims ...
                                   uncontract_dims(i) ];
                end
            end
            % reset newmodel's factors
            newmodel.factors = [];
            % stores factors which will contribute to the temporary
            % factor
            tmp_factor_parents = [];
            % populate newmode.factors with factors independant
            % from uncontraction operation
            for fi = 1:length(orig_model.factors)
                found = 0;
                for fdi = 1:length(orig_model.factors(fi).dims)
                    for odi = 1:length(other_dims)
                        % if any factor contains any one of the
                        % other_dims can not use it as it is, must
                        % create a temporary factor for those
                        % here we identify factors we will use
                        % without modification
                        if other_dims(odi) == ...
                                orig_model.factors(fi).dims(fdi)
                            found=1;
                            break
                        end
                    end
                    if found, break; end
                end
                if ~found
                    % if other_dims are not found in this factor then
                    % use this factor as it is in the new node
                    newmodel.factors = [newmodel.factors ...
                                        orig_model.factors(fi) ];
                else
                    % in other case this factor will be inspected
                    % further to generate temporary factor
                    tmp_factor_parents = [ tmp_factor_parents ...
                                        orig_model.factors(fi) ];
                end
            end
            % make sure factors are unique
            %newmodel.factors = unique(newmodel.factors);
            % inspect tmp_factor_parents and generate a temporary
            % model
            tmpf = TFFactor;
            tmpf.isTemp = 1;
            tmpf.name = 'tmp';
            names={};
            tmpf.dims = [];
            % add all dimensions of all parent factors
            for tfpi = 1:length(tmp_factor_parents)
                for di = 1:length(tmp_factor_parents(tfpi).dims)
                    if tmp_factor_parents(tfpi).isLatent
                        % if dimension is not one of the other_dims
                        % then add it to the temporary factor
                        found = 0;
                        for odi = 1:length(other_dims)
                            if other_dims(odi) == ...
                                    tmp_factor_parents(tfpi).dims(di)
                                found = 1;
                                break;
                            end
                        end
                        if ~found
                            % if not already added
                            found2 = 0;
                            for tmpfdind = 1:length(tmpf.dims)
                                if tmpf.dims(tmpfdind) == ...
                                        tmp_factor_parents(tfpi).dims(di)
                                    found2 = 1;
                                    break;
                                end
                            end
                            if ~found2
                                tmpf.dims = [ tmpf.dims ...
                                              tmp_factor_parents(tfpi) ...
                                              .dims(di)];
                                names = [ names ...
                                          tmp_factor_parents(tfpi) ...
                                          .dims(di).name];
                            end
                        end
                    end
                end
            end
            % if no names are found then there is no temporary
            % factor added
            if length(names)
                % make sure tmp.factor dims are unique
                %'önce'
                %tmpf.dims.name
                %tmpf.dims = unique(tmpf.dims);
                %'sonra'
                %tmpf.dims.name
                names=obj.order_dims(unique(names));
                for d = 1:length(names)
                    tmpf.name = [ tmpf.name '_' char(names(d)) ];
                end
                %tmpf.name = [tmpf.name '_minus_' ? ];
                newmodel.factors = [ newmodel.factors tmpf ];
                newmodel = newmodel.update_cost_from_latent();
            end
        end
        function [newmodel extra_mem] = contract_all(obj, contract_type, operation_type)
        % Performs all necessary contraction operations for the
        % model. If contract_type argument is equal to 'optimal'
        % then schedule_dp() is used to find the optimal (least
        % memory using) sequence and the optimal sequence is used
        % to contract all necessary dimensions. Otherwise
        % get_contraction_dims() is used to order contraction
        % operation which does not order dimensions. If
        % contract_type equals to 'full', no intermediate
        % contractions are performed, full tensor is calculated and
        % then contracted into the output tensor
        %
        % operation_type argument may be 'compute' or
        % 'mem_analysis'. Normal operations are performed in
        % 'compute' (default), memory usage is reported in
        % 'mem_analysis' case.
        %
        % returns the model generated after contracting all
        % necessary dimension and the total extra memory required
        % by all temporary elements
            if nargin < 3
                operation_type = 'compute';
            end
            if nargin < 2
                contract_type = 'standard';
            end
            if strcmp( contract_type, 'optimal' )
                contract_dims = ...
                    obj.get_optimal_contraction_sequence_dims(operation_type);
                %for i=1:length(contract_dims)
                %    display(['optimal contracting ' ...
                %             char(contract_dims{i})]);
                %end
            elseif  ~strcmp( contract_type, 'full' )
                contract_dims = obj.get_contraction_dims();
                %for i=1:length(contract_dims)
                %    display(['contracting ' contract_dims(i).name]);
                %end
            end
            extra_mem = 0;
            newmodel = obj;
            if strcmp( contract_type, 'full')
                [ newmodel e_m ] = obj.contract_full(operation_type);
                extra_mem = extra_mem + e_m;
            else
                for i = 1:length(contract_dims)
                    [ newmodel e_m ]= ...
                        newmodel.contract(contract_dims(i), ...
                                          operation_type);
                    extra_mem = extra_mem + e_m;
                end
            end
        end
        function [newmodel extra_mem] = contract_full(obj, operation_type)
        % generates a new full (temporary) tensor, multiplies all
        % latent tensors in to the full tensor and then
        % contracts full tensor over necessary indices and returns
        % newmodel with full_tensor in it
            % generate full tensor
            F = TFFactor;
            F.name = 'full_tensor';
            F.isTemp = 1;
            F.dims = obj.dims;    % full indices
            if strcmp( operation_type, 'compute' )
                % generate global full_tensor_data
                global full_tensor_data;
                sz = '';
                for adi = 1:length(obj.dims)
                    if adi ~= 1
                        sz = [sz ', '];
                    end
                    sz = [sz num2str(obj.dims(adi).cardinality) ];
                end
                eval( [ ' full_tensor_data = ones(' sz ');'] );
            end
            extra_mem = F.get_element_size();
            if strcmp( operation_type, 'compute' )
                % access global data of all latent factors
                lfi = obj.latent_factor_indices;
                for lfii = 1:length(lfi)
                    eval(['global ' ...
                          obj.factors(lfi(lfii)).get_data_name() ...
                         ]);
                end
                % multiply all latent tensors, store result in data_F
                for lfii = 1:length(lfi)
                    % following tensors should be multiplied with data_F
                    eval([ 'full_tensor_data = bsxfun(@times, full_tensor_data, ' ...
                           obj.factors(lfi(lfii)).get_data_name() ');' ]);
                end
                % contract necessary dimensions from full_tensor_data
                contract_dims = obj.get_contraction_dims();
                for cdi = 1:length(contract_dims)
                    full_tensor_data = sum( full_tensor_data,        ...
                                            obj.get_dimension_index( ...
                                                contract_dims(cdi)) );
                end
            end
            % create and return a newmodel compatible with other
            % contract functions
            newmodel = obj;
            newmodel.factors = [ obj.observed_factor F ];
        end
        function [newmodel extra_mem] = contract(obj, dim, operation_type)
        % returns a new TFModel generated by contracting obj with
        % dim which may add new temporary factors and mem_delta
        % integer value. extra_mem will be positive if a temporary
        % factor is generated and its value will indicate memory
        % usage of new factor. mem_delta will be zero if no
        % temporary factors are generated.
        % dim: TFDimension or char array or cell with the name of
        % the dimension
        % operation_type: if equals to 'compute' contraction is
        % calculated. if equals to 'mem_analysis' data elements are
        % not created.
            extra_mem = 0;
            if isa(dim, 'TFDimension')
                dim = dim.name;
            elseif isa(dim, 'cell')
                dim = char(dim{1});
            elseif ~isa(dim, 'char')
                display(['ERROR: unsupported dim type ' class(dim) ...
                         'was expecting TFDimension, cell or char ' ...
                         'array']);
                return
            end
            newmodel = obj;
            newmodel.name = [obj.name '_' dim];
            % remove dim from the new model's factors'
            contracted_factor_inds = [];
            for f = 1:length(newmodel.factors)
                if ~newmodel.factors(f).isObserved
                    ind = ...
                        newmodel.factors(f).got_dimension(char(dim));
                    if ind ~= 0
                        % remove this dimension from this factor
                        newmodel.factors(f).dims(ind) = [];
                        contracted_factor_inds = ...
                            [ contracted_factor_inds f ];
                    end
                end
            end
            % add a temporary factor including dimensions of
            % contracted factors other than contracted dimension
            tmp=TFFactor;
            tmp.isTemp = 1;
            tmp.name = 'tmp';
            names={};
            for cfii = 1:length(contracted_factor_inds)
                % for each dimension of the contracted factor
                for cfi_dim = 1:length(newmodel.factors(contracted_factor_inds(cfii)).dims)
                    found=0;
                    for ti = 1:length(tmp.dims)
                        if tmp.dims(ti) == ...
                                newmodel.factors(contracted_factor_inds(cfii)).dims(cfi_dim)
                            found=1;
                            break;
                        end
                    end
                    if found == 0
                        tmp.dims = [tmp.dims ...
                                    newmodel.factors(contracted_factor_inds(cfii)) ...
                                    .dims(cfi_dim)];
                        names=[names ...
                              newmodel.factors(contracted_factor_inds(cfii)).dims(cfi_dim).name];
                        %display(['added from factor index' ...
                        %         contracted_factor_inds(cfii)])
                        %display(['added from factor' newmodel.factors(contracted_factor_inds(cfii)).name])
                        %display(['addd dim' char(newmodel.factors(contracted_factor_inds(cfii)).dims(cfi_dim).name)])
                    end
                end
            end
            names=unique(names);
            for d = 1:length(names)
                tmp.name = [tmp.name '_' char(names(d))];
            end
            tmp.name = [tmp.name '_minus_' dim];
            if strcmp( operation_type, 'compute' )
                eval( [ 'global ' tmp.get_data_name()  ';'] );
                if length(contracted_factor_inds) == 1
                    % no multiplication
                    eval( [ 'global ' ...
                            obj.factors(contracted_factor_inds(1)) ...
                            .get_data_name() ';'] );
                    eval( [ tmp.get_data_name() ' = ' ...
                            obj.factors(contracted_factor_inds(1)) ...
                            .get_data_name() ';'] );
                else
                    % multiply first two into tmp data
                    eval( [ 'global' ...
                            ' ' obj.factors(contracted_factor_inds(1)).get_data_name() ...
                            ' ' obj.factors(contracted_factor_inds(2)).get_data_name() ';'] );
                    eval( [ tmp.get_data_name() ' = bsxfun (@times, ' ...
                            obj.factors(contracted_factor_inds(1)).get_data_name() ', '...
                            obj.factors(contracted_factor_inds(2)).get_data_name() ');' ...
                          ] );
                    % multiply tmp data with other factors
                    for cfii = 3:length(contracted_factor_inds)
                        eval( [ 'global '...
                                obj.factors(contracted_factor_inds(cfii)) ...
                                .get_data_name() ';'] );
                        eval( [ tmp.get_data_name() ' = bsxfun (@times, ' ...
                                tmp.get_data_name() ','...
                                obj.factors(contracted_factor_inds(cfii)) ...
                                .get_data_name() ');' ] );
                    end
                end
                % sum contraction dimensions on tmp data
                con_dim_index = obj.get_dimension_index(dim);
                eval( [ tmp.get_data_name() ' = sum( ' ...
                        tmp.get_data_name() ', ' ...
                        num2str(con_dim_index) ');'] );
            end
            newmodel.factors = [newmodel.factors tmp];
            extra_mem = tmp.get_element_size();
            % remove contracted factors
            % other dimensions live within the tmp factor
            removed_num=0; % removal breaks loop index
            for cfii = 1:length(contracted_factor_inds)
                newmodel.factors(contracted_factor_inds(cfii) ...
                                 - removed_num) = [];
                removed_num = removed_num + 1;
            end
        end
        function [ocs_dims] = get_optimal_contraction_sequence_dims(obj, ...
                                                              operation_type)
        % Runs schedule_dp function to generate graph with least
        % memory using contraction sequence information in it. Then
        % searches TFGraph.optimal_edges for the optimal path and
        % returns a cell list of contraction dimension names.
            global ocs_cache;
            found = false;
            for o = 1:length(ocs_cache)
                if ocs_cache(o).model == obj
                    found=true;
                    break
                end
            end
            if found
                %display('cache hit')
                %display([ 'ocs dims' ])
                ocs_dims = ocs_cache(o).ocs_dims;
                %for a =1:length(ocs_dims)
                %    ocs_dims{a}
                %end
                return
            %else
            %    display('cache miss')
            end
            graph = obj.schedule_dp(operation_type);
            t = graph.optimal_edges;
            t(t==0) = Inf;
            ocs_models = [];
            i = length(t);
            while i ~= 1
                ocs_models = [ ocs_models graph.node_list(i) ];
                i = find( t(:,i) == min(t(:, i)) );
            end
            ocs_models = [ ocs_models graph.node_list(i) ];
            ocs_dims = [];
            for i = 1:(length(ocs_models)-1)
                ocs_dims = [ ocs_dims ...
                             { setdiff( ...
                                 ocs_models(i)...
                                 .get_current_contraction_dims, ...
                                 ocs_models(i+ ...
                                            1)...
                                 .get_current_contraction_dims) }; ...
                           ];
            end
            %display([ 'cache store' ])
            %for a =1:length(ocs_dims)
            %    ocs_dims{a}
            %end
            ocs_cache = [ ocs_cache TFOCSCache(obj, ocs_dims) ];
        end
        function [obj] = update_cost_from_latent(obj)
            obj.cost = 0;
            lfi=obj.latent_factor_indices();
            for fi = 1:length(lfi)
                obj.cost = obj.cost + ...
                    obj.factors(lfi(fi)).get_element_size();
            end
        end
        function [dn fn all_edges] = print_ubigraph(obj)
        % returns a string to be used by fgplot
        % add dimension nodes
            dn = [ '[ ''' ];
            for i =1:length(obj.dims)
                if i ~= 1
                    dn = [ dn ''',''' ];
                end
                dn = [ dn obj.dims(i).name ];
            end
            dn = [ dn ''' ] ' ];
            % add factor nodes
            fn = [ '[ ''' ];
            for i =1:length(obj.factors)
                if i ~= 1
                    fn = [ fn ''',''' ];
                end
                fn = [ fn obj.factors(i).name ];
            end
            fn = [ fn ''' ] ' ];
            % add edges
            all_edges=['[ ' ];
            for d = 1:length(obj.dims)
                if d ~= 1
                    all_edges = [ all_edges ' , ' ];
                end
                edges=['[ ' ];
                % include this dimension if a factor uses it
                for f = 1:length(obj.factors)
                    for fd = 1:length(obj.factors(f).dims)
                        if obj.factors(f).dims(fd) == obj.dims(d)
                            if length(edges) ~= 2
                                edges = [ edges ''',''' ];
                            else
                                edges = [ edges '''' ];
                            end
                            edges = [ edges obj.factors(f).name ];
                        end
                    end
                end
                all_edges = [ all_edges edges ''' ]' ];
            end
            all_edges = [ all_edges ' ]' ];
        end
        function [size] = get_element_size(obj)
        % returns number of elements for this model
            size=0;
            for f = 1:length(obj.factors)
                if obj.factors(f).isObserved == 0
                    size = size + ...
                           obj.factors(f).get_element_size();
                end
            end
        end
        function [card] = get_index_card(obj, index_char)
        % returns cardinality of a given name of a dimension
            for d = 1:length(obj.dims)
                if obj.dims(d).name == index_char
                    card = obj.dims(d).cardinality;
                    break
                end
            end
        end
        function [factor] = get_first_non_observed_factor(obj)
        % returns first non observed factor index, used to return
        % index of the output factor when all latent factors are
        % contracted out. in this case only output (observed) and a
        % single temporary non-observed factors should be present
        % in the model (ie fully contracted model).
            for f = 1:length(obj.factors)
                if obj.factors(f).isObserved == 0
                    factor = obj.factors(f);
                    return
                end
            end
        end
        function [ind] = get_first_non_observed_factor_index(obj)
        % returns first non observed factor index, used to return
        % index of the output factor
            for f = 1:length(obj.factors)
                if obj.factors(f).isObserved == 0
                    ind = f;
                    return
                end
            end
        end
        function [ind] = find_cell_char(obj, chars)
        % returns index of a given char array in object's dimension array
            for ind=1:length(obj.dims)
                if obj.dims(ind).name == chars
                    return
                end
            end
            ind=0;
        end
       function [r] = get_dimension_index(obj, dim)
        % returns index of dimension dim in obj.dims if obj
1000         % contains TFDimension (or char) dim returns 0 otherwise
1001
1002             r=0;
1003             for d = 1:length(obj.dims)
1004                 if obj.dims(d) == dim
1005                     r=d;
1006                     break;
1007                 end
1008             end
1009        end
1010
1011
1012
1013
1014        function [ordered_index_chars] = order_dims(obj, ...
1015                                                     dims_array)
1016             % order given cell of dimension names according to
1017             % factor.dims order
1018
1019             tmp=cell(length(dims_array), 3);
1020
1021             tmp(:,1) = dims_array;
1022             for i = 1:length(dims_array)
1023                 tmp{i,2} = obj.get_index_card(char(dims_array(i)));
1024                 tmp{i,3} = obj.find_cell_char(char(dims_array(i))); % order of the index
1025                                                                     % in the model
1026             end
1027
1028             tmp=sortrows(tmp,3); % sort by the order of the model indices
1029             ordered_index_chars=tmp(:,1)';
1030         end
1031
1032
1033
1034
1035         function [contract_dims] = get_contraction_dims(obj)
1036         % returns cell of dimensions which must be contracted to
1037         % calculate output factor(s)
1038
1039             output_chars = {};
1040             for f=1:length(obj.factors)
1041                 if obj.factors(f).isObserved
1042
1043                     % for each dimension of this factor
1044                     for i=1:length(obj.factors(f).dims)
1045                         output_chars = [output_chars ...
1046                                         obj.factors(f).dims(i).name];
1047                     end
1048
1049                 end
1050             end
1051
1052             % contraction dimensions: alldims - output_dims
1053             contract_dims={};
1054             for d_a = 1:length(obj.dims)
1055                 found=0;
1056                 for d_o = 1:length(output_chars)
1057                     if obj.dims(d_a) == char(output_chars(d_o))
1058                         found=1;
1059                         break
1060                     end
1061                 end
1062
1063                 if found == 0
1064                     contract_dims = [contract_dims obj.dims(d_a)];
1065                     %['add '  obj.dims(d_a).name]
1066                 end
1067             end
1068
1069             %['return ' contract_dims.name]
1070             %contract_dims = obj.order_dims(unique(contract_dims));
1071         end
1072
1073
1074
1075
1076         function [contract_dims] = get_current_contraction_dims(obj)
1077         % returns cell of TFDimensions which must be contracted to
1078         % calculate output factor(s) by using current factors to
1079         % calculate all dimension not model.dims. (model.dims is always
1080         % fixed to maximum possible dimension list.)
1081
1082             output_chars = {};
1083             for f=1:length(obj.factors)
1084                 if obj.factors(f).isObserved
1085
1086                     % for each dimension of this factor
1087                     for i=1:length(obj.factors(f).dims)
1088                         output_chars = [output_chars ...
1089                                         obj.factors(f).dims(i).name];
1090                     end
1091
1092                 end
1093             end
1094
1095             % contraction dimensions: alldims - output_dims
1096             alldims={};
1097             for f = 1:length(obj.factors)
1098                 for d = 1:length(obj.factors(f).dims)
1099                     found = 0;
1100                     n=obj.factors(f).dims(d).name;
1101                     for i=1:length(alldims)
1102                         if char(alldims(i)) == n
1103                             found = 1;
1104                             break
1105                         end
1106                     end
1107
1108                     if ~found
1109                         alldims = [alldims n];
1110                     end
1111                 end
1112             end
1113
1114             contract_dims={};
1115             for d_a = 1:length(alldims)
1116                 found=0;
1117                 for d_o = 1:length(output_chars)
1118                     if char(alldims(d_a)) == char(output_chars(d_o))
1119                         found=1;
1120                         break
1121                     end
1122                 end
1123
1124                 if found == 0
1125                     contract_dims = [contract_dims alldims(d_a)];
1126                     %['add '  alldims(d_a).name]
1127                 end
1128             end
1129
1130             %['return ' contract_dims.name]
1131             %contract_dims = obj.order_dims(unique(contract_dims));
1132         end
1133
1134
1135
1136
1137         function [factor_inds] = latent_factor_indices(obj)
1138             factor_inds=[];
1139             for f=1:length(obj.factors)
1140                 if obj.factors(f).isLatent
1141                     factor_inds = [ factor_inds f ];
1142                 end
1143             end
1144         end
1145
1146
1147
1148
1149         function [factors] = latent_factors(obj)
1150             factors=[];
1151             for f=1:length(obj.factors)
1152                 if obj.factors(f).isLatent
1153                     factors = [ factors obj.factors(f) ];
1154                 end
1155             end
1156         end
1157
1158
1159
1160
1161         function [factor_ind] = observed_factor_index(obj)
1162             factor_ind=0;
1163             for f=1:length(obj.factors)
1164                 if obj.factors(f).isObserved
1165                     factor_ind = f;
1166                     return
1167                 end
1168             end
1169         end
1170
1171
1172
1173
1174         function [factor] = observed_factor(obj)
1175         % returns first observed factor (useful for PLTF operations)
1176             for f=1:length(obj.factors)
1177                 if obj.factors(f).isObserved
1178                     factor = obj.factors(f);
1179                     return
1180                 end
1181             end
1182         end
1183
1184
1185
1186
1187         function [factors] = observed_factors(obj)
1188             factors=[];
1189             for f=1:length(obj.factors)
1190                 if obj.factors(f).isObserved
1191                     factors = [ factors obj.factors(f) ];
1192                 end
1193             end
1194         end
1195
1196
1197
1198
1199         function [factors] = input_factors(obj)
1200             factors=[];
1201             for f=1:length(obj.factors)
1202                 if obj.factors(f).isInput
1203                     factors = [ factors obj.factors(f) ];
1204                 end
1205             end
1206         end
1207
1208
1209
1210
1211         function [factors] = temp_factors(obj)
1212             factors=[];
1213             for f=1:length(obj.factors)
1214                 if obj.factors(f).isTemp
1215                     factors = [ factors obj.factors(f) ];
1216                 end
1217             end
1218         end
1219
1220
1221
1222
1223         function [] = rand_init_latent_factors(obj, type, imax)
1224
1225             if ~strcmp(type, 'all') && ~strcmp(type, 'nonClamped')
1226                 throw(MException('TFModel:WrongInitType', ...
1227                                  ['Supported init type values: all, ' ...
1228                                   'nonClamped']));
1229             end
1230
1231             for fi=1:length(obj.latent_factor_indices)
1232
1233                 if strcmp(type, 'all') || ...
1234                         (strcmp(type, 'nonClamped') && ...
1235                           obj.factors(fi).isInput == 0)
1236
1237                     if nargin==2
1238                         obj.factors(fi).rand_init(obj.dims);
1239                     else
1240                         obj.factors(fi).rand_init(obj.dims, imax);
1241                     end
1242
1243                 end
1244             end
1245
1246         end
1247
1248
1249
1250         function [r] = eq(a,b)
1251             r = false;
1252
1253             % mark matched b factors
1254             % if there are any unmarked -> inequal
1255             % problematic case:
1256             % a.factors (ip, jpi) , b.factors (ip, pi)
1257             % b==a matches all b objects with a.factors(1)
1258             % but a~=b !
1259
1260             b_marks = zeros(size(b.factors));
1261
1262             if length(a.factors) == length(b.factors)
1263                 for f_a = 1:length(a.factors)
1264                     found = 0;
1265                     for f_b = 1:length(b.factors)
1266                         if a.factors(f_a) == b.factors(f_b) && ...
1267                                 b_marks(f_b) == 0
1268                             found = 1;
1269                             b_marks(f_b) = 1;
1270                             break
1271                         end
1272                     end
1273
1274                     if found == 0
1275                         return
1276                     end
1277                 end
1278
1279                 r = true;
1280             end
1281         end
1282
1283
1284
1285
1286         function [uncontraction_dims] = get_uncontraction_dims(obj)
1287         % returns list of TFDimension objects representing
1288         % dimensions which are required to be added to the current
1289         % TFModel object in order to reach initial model where
1290         % uncontraction_dims = {}
1291         % Calculation is performed as follows:
1292         % uncontraction_dims = contraction_dims - current_contraction_dims
1293
1294             contraction_dims = obj.get_contraction_dims();
1295             current_contraction_dims = ...
1296                 obj.get_current_contraction_dims();
1297             uncontraction_dims = [];
1298
1299             for cdi = 1:length(contraction_dims)
1300                 found=0;
1301                 for ccdi = 1:length(current_contraction_dims)
1302                     if contraction_dims(cdi) == ...
1303                             char(current_contraction_dims(ccdi))
1304                         found=1;
1305                         break;
1306                     end
1307                 end
1308                 if ~found
1309                     uncontraction_dims = [ uncontraction_dims ...
1310                                         contraction_dims(cdi) ];
1311                 end
1312             end
1313         end
1314
1315
1316     end
1317
1318
1319 end