Description of TFOCSCache
TFOCSCache
PURPOSE
Represents cached search results for optimal contraction sequence search operation
SYNOPSIS
This is a script file.
DESCRIPTION
 Represents cached search results for optimal contraction sequence search operation
   get_optimal_contraction_sequence_dims function searches for
   optimal contraction sequence using schedule_dp. Over iterations
   of PLTF same search operation must be conducted several
   times. This object stores generated values to be used again in
   following operations
 See also TFModel
CROSS-REFERENCE INFORMATION
This function calls:
TFModel Represents data required to describe a tensor factorization model
TFOCSCache Represents cached search results for optimal contraction sequence search operation
This function is called by:
TFModel Represents data required to describe a tensor factorization model
TFOCSCache Represents cached search results for optimal contraction sequence search operation
SUBFUNCTIONS
function obj = TFOCSCache(model, ocs_dims)
SOURCE CODE
% Represents cached search results for optimal contraction sequence search operation
%   get_optimal_contraction_sequence_dims function searches for
%   optimal contraction sequence using schedule_dp. Over iterations
%   of PLTF same search operation must be conducted several
%   times. This object stores generated values to be used again in
%   following operations
%
% See also TFModel
classdef TFOCSCache
    properties
        model = TFModel;
        ocs_dims = {};
    end
    methods
        function obj = TFOCSCache(model, ocs_dims)
            obj.model = model;
            obj.ocs_dims = ocs_dims;
        end
    end
end